pipeline_steps:
  embedder:
    step:
      global_extractor:
        _target_: mts.core.embedder.vlad.NetVladEmbedding
        model_location: model-weights/net-vlad

  pairing:
    cutoff_th: 1.25
    distance_th: 10
    min_pairs: 1
    max_pairs_per_image: 30
    max_pairs: 2000