name: IMC2025
description: |
  Use NetVLAD global descriptors + kNN for pair creation
  Use MASt3R two-step matcher (encode-once, decode-per-pair) for dense keypoint matching
  Use ColmapReconstructionStep for incremental 3D reconstruction

project_path: iterations
data_dirpath: "data/image-matching-challenge-2025"
sample_filepath: null
run_type: train
origin: None
git_commit: None
datasets_names: null
save_project_to_git: False
submission_dest_dirpath: null
tag: null
mark: null


pipeline_steps:
  embedder:
    _target_: mts.pipeline.step.base.OnDeviceRunner
    device: cuda:0
    step:
      _target_: mts.pipeline.step.extract.embedding.base.GlobalDescriptorStep
      global_extractor:
        _target_: mts.core.embedder.vlad.NetVladEmbedding
        model_location: model-weights/net-vlad

  pairing:
    _target_: mts.pipeline.step.pair.knn.KnnEmbeddingParerStep
    k: 20
    min_distance_th: 0.0
    distance_th: 10
    max_pairs_per_image: 15
    max_pairs: 1000

  kp_matching:
    _target_: mts.pipeline.step.base.OnDeviceRunner
    device: cuda:0
    step:
      _target_: mts.pipeline.step.match.mast3r.two_steps.Mast3rMatchPipelineStep.from_checkpoint
      grow_graph:
        _target_: mts.core.scene_graph.transient.grow_densely
        _partial_: true
      mast3r_model_checkpoint: "model-weights/mast3r/MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric.pth"
      image_size: 512
      min_pairs: 50
      match_conf_th: 0.8
      pixel_tol: 16

  reconstruction:
    _target_: mts.pipeline.step.reconstruct.colmap.incremental.ColmapReconstructionStep
    keypoints_name: mast3r
    matches_name: mast3r
    mapper_options:
      _target_: mts.helpers.colmap.options.create_incremental_pipeline_options
      min_model_size: 3
      max_num_models: 25


reconstruction_runner:
  create_pipeline_method: app.imc2025.pipeline.create_pipeline
  create_repository_method: app.imc2025.pipeline.create_h5_repository
  create_pipeline_state_method: app.imc2025.pipeline.create_pipeline_state
