name: IMC2025
description: |
  Use SiftDistanceParer (DINOv2 global + SIFT validation) for pair creation
  Use SiftKeypointMatchStep for CPU-based SIFT extraction and matching
  Use ColmapReconstructionStep for incremental 3D reconstruction

project_path: iterations
data_dirpath: "data/image-matching-challenge-2025"
sample_filepath: null
is_train: True
origin: None
git_commit: None
datasets_names: null
save_project_to_git: False
submission_dest_dirpath: null


pipeline_steps:
  paring:
    _target_: mts.pipeline.step.base.OnDeviceRunner
    device: cuda:0
    step:
      _target_: mts.pipeline.step.pair.sift.SiftDistanceParer
      save_keypoints: True
      save_descriptors: True
      save_matches: True
      dinov2_global_descriptor:
        _target_: mts.core.embedder.dinov2.DinoV2GlobalDescriptors.from_pretrained
        model_location: model-weights/fb-dinov2/snapshots/f9e44c814b77203eaa57a6bdbbd535f21ede1415

  kp_matching:
    _target_: mts.pipeline.step.match.sift.SiftKeypointMatchStep
    num_features: 2048
    ratio_threshold: 0.75
    min_matches: 30

  reconstruction:
    _target_: mts.pipeline.step.reconstruct.colmap.incremental.ColmapReconstructionStep
    keypoints_name: sift
    descriptors_name: sift
    matches_name: sift
    mapper_options:
      _target_: mts.helpers.colmap.options.create_incremental_pipeline_options
      min_model_size: 3
      max_num_models: 25

reconstruction_runner:
  create_pipeline_method: app.imc2025.pipeline.create_pipeline
  create_repository_method: app.imc2025.pipeline.create_h5_repository
  create_pipeline_state_method: app.imc2025.pipeline.create_pipeline_state
