[project]
name = "dancing-dots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "build>=1.4.0",
    "click>=8.3.3",
    "einops>=0.8.1",
    "faiss-cpu>=1.13.2",
    "h5py==3.16.0",
    "hydra-core>=1.3.2",
    "kornia>=0.8.2",
    "pillow==12.0.0",
    "more-itertools>=10.8.0",
    "numpy==2.3.4",
    "pandas==2.3.3",
    "pycolmap==3.13.0",
    "shapely==2.1.2",
    "torch==2.5.1",
    "tqdm>=4.67.1",
    "transformers==4.57.1",
    "huggingface_hub==0.36.2",
    "trimesh>=4.0.0",
    "manifold3d>=3.0.0",
    # Local packages
    # wheels
    "croco",
    "dust3r",
    "mast3r",
    # submodules
    "gim",
    "lightglue",
    "asmk",
    "romatch",
]

[project.optional-dependencies]
kaggle = [
    "kagglehub>=0.3",
]

[dependency-groups]
build = [
    "setuptools>=80.9.0",
]
dev = [
    "streamlit>=1.45.0",
    "py3nvml==0.2.7",
    "nbformat==5.10.4",
    "transformers==4.57.1",
     "hloc",
    "cython>=3.2.4",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "plotly==6.4.0",
    "kaleido>=1.0.0",
    "pip>=25.3",
]
[tool.uv]
package = true
override-dependencies = [
    "lightglue",
]

[tool.uv.extra-build-dependencies]
asmk = [
    "setuptools",
    "faiss-cpu>=1.13.2",
]

[project.scripts]
run-on-mps = "app.imc2025.run.on_mps:main"
run = "app.imc2025.run.run:main"
run-matrix = "app.imc2025.run.matrix:main"
run-distributed = "app.imc2025.run.distributed:main"
launch-distributed = "app.imc2025.run.launch:main"
run-from-iteration = "app.imc2025.run.from_iteration:main"
upload-dataset-to-kaggle = "scripts.kaggle.upload_dataset:main"
upload-model-weights-to-kaggle = "scripts.kaggle.upload_model_weights:main"
download-iteration-from-kaggle = "scripts.kaggle.download_iteration:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
app = ["logging/*.yaml"]

[tool.uv.sources]
hloc = { git = "https://github.com/cvg/Hierarchical-Localization.git" }
croco = { path = "deps/whls/croco-0.1.2-py3-none-any.whl" }
dust3r = { path = "deps/whls/dust3r-0.1.0-py3-none-any.whl" }
mast3r = { path = "deps/whls/mast3r-0.1.0-py3-none-any.whl" }
asmk = { path = "deps/submodules/asmk" }
lightglue = { path = "deps/submodules/lightglue", editable = true}
gim = { path = "deps/submodules/gim", editable = true }
