data_dirpath: "/kaggle/input/competitions/image-matching-challenge-2025-ongoing"
submission_dest_dirpath: "/kaggle/working"

pipeline_steps:
  global_embedding:
    step:
      global_extractor:
        torch_hub_dir: /kaggle/input/models/hantig/netvlad/pytorch/default/1
